# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(choices=[(1, 'Music'), (2, 'Text')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
