# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160626_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='api_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
