# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160626_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='api_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
